---
# Main tasks file for get_domains role
- name: Get all FMC domains
  cisco.fmcansible.fmc_configuration:
    operation: getAllDomain
    register_as: "{{ register_as }}"
  register: domain_result

- name: Set domains fact
  set_fact:
    "{{ register_as }}": "{{ domain_result.response.items }}"

- name: Save domains to JSON file
  copy:
    content: "{{ domain_result.response | to_nice_json }}"
    dest: "{{ output_dir }}/fmc_domains.json"
  delegate_to: localhost
  when: save_to_file | bool

- name: Display found domains
  debug:
    msg: "Found {{ domain_result.response.items | length }} domain(s): {{ domain_result.response.items | map(attribute='name') | list | join(', ') }}"
